version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: berlin-transport-nginx-cloud
    restart: unless-stopped
    ports:
      - "80:80"   
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/logs:/var/log/nginx
    depends_on:
      - backend
      - frontend
  
  backend:
    build:
      context: ./web/backend
      dockerfile: Dockerfile
    container_name: berlin-transport-backend-cloud
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=5000
      - JWT_SECRET=${JWT_SECRET}
      - DB_HOST=${DB_HOST}  # Same Neo4j Aura connection
      - DB_PASSWORD=${DB_PASSWORD}  # Same Neo4j Aura password
    volumes:
      - ./logs/backend:/usr/src/app/logs
      - ./web/backend/public:/usr/src/app/public

  frontend:
    build:
      context: ./web/frontend
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
    container_name: berlin-transport-frontend-cloud
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - NEXTAUTH_URL=https://berlin-transport-history.de
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - JWT_SECRET=${JWT_SECRET}