version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: berlin-transport-nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/logs:/var/log/nginx
    depends_on:
      - backend
      - frontend
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 128M
        reservations:
          memory: 64M

  backend:
    build:
      context: ./web/backend
      dockerfile: Dockerfile
    container_name: berlin-transport-backend
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=5000
      - JWT_SECRET=${JWT_SECRET}
      - DB_HOST=${DB_HOST}
      - DB_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./logs/backend:/usr/src/app/logs
      - ./web/backend/public:/usr/src/app/public
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
        reservations:
          memory: 256M

  frontend:
    build:
      context: ./web/frontend
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
    container_name: berlin-transport-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"  # Add this for direct access
    environment:
      - NODE_ENV=production
      - NEXTAUTH_URL=https://berlin-transport-history.de
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - JWT_SECRET=${JWT_SECRET}
      - NEO4J_AURA_URI=${NEO4J_AURA_URI}
      - NEO4J_AURA_USERNAME=${NEO4J_AURA_USERNAME}
      - NEO4J_AURA_PASSWORD=${NEO4J_AURA_PASSWORD}
    # Remove volume mounting for production
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
        reservations:
          memory: 256M

  neo4j:
    image: neo4j:5.13.0
    container_name: berlin-transport-db
    ports:
      - "7474:7474"
      - "7473:7473"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/BerlinTransport2024
      - NEO4J_server_memory_heap_initial__size=512m
      - NEO4J_server_memory_heap_max__size=1G
      - NEO4J_server_memory_pagecache_size=512m
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_server_default__listen__address=0.0.0.0
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      - neo4j_import:/import
      - neo4j_plugins:/plugins
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '2.5'
          memory: 2G
        reservations:
          memory: 1G
    healthcheck:
      test: ["CMD-SHELL", "cypher-shell -u neo4j -p BerlinTransport2024 'RETURN 1' || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

volumes:
  neo4j_data:
  neo4j_logs:
  neo4j_import:
  neo4j_plugins: